CHAL := $(notdir $(DIR))
DOCKER_IMAGE := speedrun-$(CHAL)
DOCKER_PORTS := 300$(CHAL)
DOCKER_TIMELIMIT := 30
DOCKER_CHALLENGE_NAME := chall_$(CHAL)
DOCKER_CHALLENGE_PATH := $(DIR)/$(DOCKER_CHALLENGE_NAME)

PUBLISH := chall_$(CHAL)
